name: npm CI

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - id: npm_build
        name: Build with npm
        env:
          REMOTE_NPM_REGISTRY_URL: ${{ secrets.REMOTE_NPM_REGISTRY_URL }}
        run: |
          chmod +x ./scripts/github/*.sh
          ./scripts/github/build.sh
      - name: Merge the changes into npm registry and publish
        env:
          IS_DEVELOPMENT_VERSION: ${{ steps.npm_build.outputs.IS_DEVELOPMENT_VERSION }}
        run: |
          ./scripts/github/publish.sh

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
